export const fruitNames: string[] = [
    'Açaí',
    'Apple',
    'Akee',
    'Apricot',
    'Avocado',
    'Banana',
    'Bell pepper',
    'Bilberry',
    'Blackberry',
    'Blackcurrant',
    'Black sapote',
    'Blood orange',
    'Blueberry',
    'Boysenberry',
    "Buddha's hand",
    'Cantaloupe',
    'Crab apples',
    'Currant',
    'Cherry',
    'Cherimoya',
    'Chico fruit',
    'Chili pepper',
    'Clementine',
    'Cloudberry',
    'Coconut',
    'Corn kernel',
    'Cranberry',
    'Cucumber',
    'Damson',
    'Date',
    'Dragonfruit',
    'Durian',
    'Eggplant',
    'Elderberry',
    'Feijoa',
    'Fig',
    'Goji berry',
    'Gooseberry',
    'Grape',
    'Grapefruit',
    'Guava',
    'Honeyberry',
    'Honeydew',
    'Huckleberry',
    'Jabuticaba',
    'Jackfruit',
    'Jambul',
    'Japanese plum',
    'Jostaberry',
    'Jujube',
    'Juniper berry',
    'Kiwano',
    'Kiwifruit',
    'Kumquat',
    'Lemon',
    'Lime',
    'Loquat',
    'Longan',
    'Lychee',
    'Mandarine',
    'Mango',
    'Mangosteen',
    'Marionberry',
    'Melon',
    'Miracle fruit',
    'Mulberry',
    'Nectarine',
    'Nance',
    'Olive',
    'Orange',
    'Papaya',
    'Pitaya',
    'Passionfruit',
    'Pea',
    'Peach',
    'Pear',
    'Persimmon',
    'Plantain',
    'Plum',
    'Prune',
    'Pineapple',
    'Pineberry',
    'Plumcot',
    'Pomegranate',
    'Pomelo',
    'Pumpkin',
    'Purple mangosteen',
    'Quince',
    'Raisin',
    'Raspberry',
    'Rambutan',
    'Redcurrant',
    'Salal',
    'Salak',
    'Salmonberry',
    'Satsuma',
    'Soursop',
    'Squash',
    'Star apple',
    'Star fruit',
    'Strawberry',
    'Surinam cherry',
    'Tamarillo',
    'Tamarind',
    'Tangerine',
    'Tomato',
    'Ugli fruit',
    'Watermelon',
    'White currant',
    'White sapote',
    'Yuzu',
    'Zucchini',
]
